
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "../GameObject.sol";
import "../IGameObject.sol";

contract BaseUnit is GameObject {
  constructor(uint hp, uint armor) public {
    setHealth(100);
    setArmor(20);
  }
  function attack(IGameObject opponent) virtual public {
    
  }
}
