
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "./BaseUnit.sol";

contract WarriorUnit is BaseUnit {
  constructor(uint hp, uint armor)  public {
    setHealth(100);
    setArmor(20);
    setPower(50);
  }
}
